Add `openwrt-25.12` branch, bump actions versions

diff --git a/nfqws/files/nfqws b/nfqws/files/nfqws
--- a/nfqws/files/nfqws
+++ b/nfqws/files/nfqws
@@ -14,6 +14,7 @@ start() {
     return 1
   fi
 
+  nft delete table inet zapret || true
   nft create table inet zapret
   nft add chain inet zapret post "{type filter hook postrouting priority mangle;}"
   nft add rule inet zapret post meta mark and 0x40000000 == 0 tcp dport "{80,443}" ct original packets 1-6 queue num 200 bypass
@@ -23,9 +24,13 @@ start() {
 
   sysctl net.netfilter.nf_conntrack_tcp_be_liberal=1 >/dev/null
 
-  "$SCRIPT" @"$CONFIG"
+  if "$SCRIPT" @"$CONFIG"; then
+    echo 'Started nfqws service'
+  else
+    echo 'Service nfqws is failed' >&2
+    return 1
+  fi
 
-  echo 'Started nfqws service'
 }
 
 stop() {
